### PR TITLE
Drop coveralls (the service)

### PR DESCRIPTION
**Pull request by suligap**
It wasn't really used (not configured) it turns out.

> You have to provide either repo_token in .coveralls.yml, or launch via Travis

### CODE REVIEW

**Comment by doismellburning** [comment]
Er, we _do_ launch via Travis...!

**Comment by doismellburning** [comment]
Ahhh!

We don't pin the version of tox we install on `.travis.yml`, we just `pip install tox`.

With tox 2, not all environment variables are passed through by default, thus https://github.com/coagulant/coveralls-python#usage-tox--v20 has `passenv`!

**Comment by doismellburning** [comment]
#48, if you would please?

**Comment by suligap** [comment]
Good spot! Closing this as obsoleted by #48

**Pull request closed without merging**
