### PR TITLE
Log request errors with exception log level.

### PR DESCRIPTION
**Pull request by suligap**
Also:
- simplify error handling (drop `except URLError` block)
- add error repr to the status message.

### CODE REVIEW

**Comment by doismellburning** [comment]
Cripes didn't realise we had a bare `except` in there!

Things like `NameError` (as in `NameError: name 'badgerbadger' is not defined`) are instances of `Exception` too. I think it might be better to leave the bare `except` in there, as a "ew we should fix this properly" placeholder, rather than changing it to `except Exception` (which looks far more..."deliberate") - though by all means drop that `URLError` catch! Your thoughts?

**Comment by suligap** [comment]
I think the whole concept of:

1. try to make a request
2. if it fails pretend that the api responded with some sort of error status (even if there was no real response)

is wrong. This is just a quick fix to simplify and add better logging.

Sure, we can go back to bare `except` although I'm not sure if it `except Exception` looks less bad ;)

**Comment by doismellburning** [comment]
Absolutely agree that there's deeper problems to be fixed outside this PR!

As for `except Exception`, I'm not just considering humans (though I'd certainly look askance at it outside of Special Circumstances), but also I think pylint and friends wouldn't warn on it (for similar reasons)

**Comment by suligap** [comment]
Yes, good point.

**Comment by doismellburning** [comment]
Awesome, cheers!

**Pull request merged**
