### PR TITLE
Fixes for Python 3

### PR DESCRIPTION
**Pull request by MarkusH**

### CODE REVIEW

**Comment by doismellburning** [comment]
...is this identifying a bunch of missing test coverage?

**Comment by doismellburning** [comment]
@MarkusH This has been open for 3 weeks now; do you think you could nudge it along in some appropriate fashion please?

**Comment by MarkusH** [comment]
@doismellburning Yes, we're missing a bunch of tests for those code paths.

**Comment by MarkusH** [comment]
There you go @doismellburning

**Comment by doismellburning** [comment]
Awesome, cheers

**Pull request merged**
