### PR TITLE
Use twine instead of setuptools for package uploads

### PR DESCRIPTION
**Pull request by MarkusH**
This ensures a secure communication channel

### CODE REVIEW

**Comment by slafs** [comment]
Are we actually using pip when doing `python setup.py register upload`? Looks like the title is misleading. And too long for a git commit subject line.

**Comment by MarkusH** [comment]
Good point, @slafs Thanks!

**Comment by MarkusH** [comment]
Updated, @slafs ! Thanks!

**Comment by slafs** [comment]
:+1:

**Pull request merged**
