### PR TITLE
Keep signing.sign generic

### PR DESCRIPTION
**Pull request by suligap**
Removes assumptions from there which do not belong inside
this function.

Given that this might be considered as a backwards incompatible
change this should be included in a next major release.

### CODE REVIEW

**Comment by doismellburning** [comment]
@suligap Am I right in thinking the WIP is because of the compatibility implications, or is there anything else?

**Comment by suligap** [comment]
Correct.

**Comment by doismellburning** [comment]
@suligap This has been open for 21 days; I'd love to see it go in somehow rather than sit unmerged, but I totally appreciate your compatibility concerns.

What worries me is that it's a compatibility change that, if you don't account for it, manifests itself as a sudden surprise change in signature generated - no runtime error, nothing up-front, just silent subtle change that will be problematic later.

What do you think about changing this such that it doesn't break compatibility (e.g. with an optional parameter defaulting to old behaviour and logging a deprecation warning)? Or, well, almost anything else to cut down on user-surprise?

**Comment by suligap** [comment]
> What do you think about changing this such that it doesn't break compatibility (e.g. with an optional parameter defaulting to old behaviour and logging a deprecation warning)? Or, well, almost anything else to cut down on user-surprise?

Thanks. Yes! I'm all for deprecating it first (give the users some time to adjust) - but still removing the whole thing eventually in a later major release. I believe this logic shouldn't have been introduced in the first place and that `sign()` should be as simple as possible. Is this what you're proposing?

Closing this for now.

**Comment by doismellburning** [comment]
> I believe this logic shouldn't have been introduced in the first place and that sign() should be as simple as possible

I don't dispute that at all - I completely support the intentions behind the change!

My concerns are about anyone who updates and doesn't notice the change; the only way you'd find out is suddenly getting signature mismatches, and signature mismatches aren't the most fun thing to debug

**Comment by suligap** [comment]
Yes, that's a very good point which was ignored by this PR - I jumped straight to the complete removal without introducing a deprecation period. Thanks again :)

**Pull request closed without merging**
